# Default values for eck-cr.
# This is a YAML-formatted file.

fullnameOverride: ""
protocol: http
httpPort: 9200
transportPort: 9300

service:
  labels: {}
  labelsHeadless: {}
  type: ClusterIP
  nodePort: ""
  annotations: {}
  httpPortName: http
  transportPortName: transport
  loadBalancerIP: ""
  loadBalancerSourceRanges: []

elasticsearch:
  enabled: true
  name: "elasticsearch"
  version: 7.6.1
  http:
  image:  
  nodeSets:
  - name: master
    count: 1
    config:
      node.master: true
      node.data: true
      node.ingest: false
      xpack.ml.enabled: true
      node.store.allow_mmap: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: default
  podDisruptionBudget:
  secureSettings:
  updateStrategy:




kibana:
  enabled: false
  version: 7.6.1
  http:
    service:
      spec:
        type: LoadBalancer
  image:
  count: 1
  config:
  elasticsearchRef:
    name: "elasticsearch-cluster"   
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          requests:
            memory: 512Mi
            cpu: 0.5
          limits:
            memory: 512Mi
            cpu: 0.5
  secureSettings:


ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

