# Default values for eck-cr.
# This is a YAML-formatted file.
elasticsearch:
  enabled: true
  name: elasticsearch
  version: 7.6.1
  http:
  image:  
  nodeSets:
  - name: master
    count: 1
    config:
      node.master: true
      node.data: true
      node.ingest: false
      xpack.ml.enabled: true
      node.store.allow_mmap: false
    podTemplate:
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    elasticsearch.k8s.elastic.co/cluster-name: quickstart
                topologyKey: kubernetes.io/hostname
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms1g -Xmx1g
          resources:
            requests:
              memory: 1Gi
              cpu: 0.5
            limits:
              memory: 1Gi
              cpu: 1
  podDisruptionBudget:
  secureSettings:
  updateStrategy:




kibana:
  enabled: true
  version: 7.6.1
  http:
    service:
      spec:
        type: LoadBalancer
  image:
  count: 1
  config:
  elasticsearchRef:
    name: "elasticsearch-cluster"   
  podTemplate:
    spec:
      containers:
      - name: kibana
  secureSettings:



