apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: elasticsearch
  namespace: elastic-system
spec:
  tls:
    - hosts:
      - ubuntu
      secretName: tls-secret
  rules:
    - host: ubuntu
      http:
        paths:
          - path: /
            backend:
              serviceName: elasticsearch-cluster-es-http
              servicePort: 9200
